### ISSUE TITLE
Please 

### ISSUE THREAD

**Issue by script-hacker48** [Brhamix/referral-code-generator#1]
This is not working in termux
Please help me

**Comment by kodegrenade** [comment]
What kind of error did you get while using it?

**Comment by script-hacker48** [comment]
When i am putting this code on temrux every time i am getting error
I erase my termux data and again try but not working ![Screenshot_20221023_170155_com.termux.jpg](https://user-images.githubusercontent.com/116253806/197389705-16301a66-1b70-4c1c-878c-1e6d92bd3213.jpg)

**Comment by kodegrenade** [comment]
Ensure you have `npm` and `nodejs` installed on the app.
The package works fine on `nodejs` enabled environment. The issue is with your implementation.

**Comment by script-hacker48** [comment]
I have install this all thing already in temrux

**Comment by kodegrenade** [comment]
Okay. Take your time and review your codebase for possible errors.

**Comment by script-hacker48** [comment]
But man I don't know programming well I am just start learning
Can you solve it

**Comment by kodegrenade** [comment]
I'm not familiar with `Termux`, hence the reason I'm unable to suggest a possible solution.
Cheers.

**Comment by script-hacker48** [comment]
Okey,
Well If I want to do this then How can i do?
Means, if you want to do this form which software you will do??

**Comment by kodegrenade** [comment]
Kindly do some search on google for more insights.

**Comment by script-hacker48** [comment]
> Kindly do some search on google for more insights.

OK man.
